bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 AbdominalFatWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 CombHeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Day45BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Day90BodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 DressingPercentage
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 EvisceratedWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 HeartWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 InitialBodyWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 LiverWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 ShankLength
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 SlaughterWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 SpleenWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 TestisWeight
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week10FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week11FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week12FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week13FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week5FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week5to7DailyGain
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week5to7FeedEfficiency
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week5to7TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week5to90TotalFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week6FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week7FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week8FeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 1 4 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 5 8 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 9 12 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 13 16 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 17 20 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 21 24 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 25 28 Week10to13DailyFeedIntake
bash /soft/zhh/vQTL/Coloc/run_coloc_1.sh 29 32 Week10to13DailyFeedIntake
